import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const TOKENS_PATH = path.resolve(__dirname, '../src/design-tokens/tokens.json');
const OUTPUT_PATH = path.resolve(__dirname, '../src/styles/theme-tokens.css');

/**
 * Enterprise Design Tokens Transformation Engine
 * Reads W3C / Figma Tokens JSON format and emits Tailwind CSS v4 @theme CSS Custom Properties.
 */
function transformTokens() {
  console.log('[Design Tokens Pipeline] Loading tokens from:', TOKENS_PATH);

  if (!fs.existsSync(TOKENS_PATH)) {
    throw new Error(`Token definition file not found at ${TOKENS_PATH}`);
  }

  const raw = fs.readFileSync(TOKENS_PATH, 'utf-8');
  const tokenData = JSON.parse(raw);
  const { tokens } = tokenData;

  const lines = [];
  lines.push('/**');
  lines.push(' * AUTO-GENERATED BY scripts/transform-tokens.mjs');
  lines.push(' * SINGLE SOURCE OF TRUTH: src/design-tokens/tokens.json');
  lines.push(' * DO NOT EDIT DIRECTLY. Run `npm run tokens:build` to regenerate.');
  lines.push(` * Generated at: ${new Date().toISOString()}`);
  lines.push(' */');
  lines.push('');
  lines.push('@theme {');

  // 1. Typography Fonts
  if (tokens.typography?.fontFamily) {
    lines.push('  /* Typography Tokens */');
    for (const [key, item] of Object.entries(tokens.typography.fontFamily)) {
      lines.push(`  --font-${key}: ${item.value};`);
    }
    lines.push('');
  }

  // 2. Micro-typography Scale
  if (tokens.typography?.fontSize) {
    lines.push('  /* Micro-typography Scale */');
    for (const [key, item] of Object.entries(tokens.typography.fontSize)) {
      lines.push(`  --text-${key}: ${item.value};`);
      if (item.lineHeight) {
        lines.push(`  --text-${key}--line-height: ${item.lineHeight};`);
      }
    }
    lines.push('');
  }

  // 3. Spacing Scale Tokens
  if (tokens.spacing) {
    lines.push('  /* Spacing Scale Tokens */');
    for (const [key, item] of Object.entries(tokens.spacing)) {
      lines.push(`  --spacing-${key}: ${item.value};`);
    }
    lines.push('');
  }

  // 4. Color Tokens (Recursive / Nested Group flattening)
  if (tokens.color) {
    lines.push('  /* Brand & Semantic Color Tokens */');
    function processColorGroup(obj, prefix = '--color') {
      for (const [key, val] of Object.entries(obj)) {
        if (val && typeof val === 'object' && 'value' in val) {
          lines.push(`  ${prefix}-${key}: ${val.value};`);
        } else if (val && typeof val === 'object') {
          processColorGroup(val, `${prefix}-${key}`);
        }
      }
    }
    processColorGroup(tokens.color);
    lines.push('');
  }

  lines.push('}');
  lines.push('');

  const outputDir = path.dirname(OUTPUT_PATH);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  fs.writeFileSync(OUTPUT_PATH, lines.join('\n'), 'utf-8');
  console.log('[Design Tokens Pipeline] Successfully generated theme at:', OUTPUT_PATH);
}

try {
  transformTokens();
} catch (err) {
  console.error('[Design Tokens Pipeline] Error during token transformation:', err);
  process.exit(1);
}
